name: .NET

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --output release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Branch name
      run: echo '${{ env.GITHUB_REF }}'
    - name: Zip
      run: tar -a -c -f ${{ env.GITHUB_REF }}.zip release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifact: '${{ env.GITHUB_REF }}.zip'
        token: ${{ secrets.GITHUB_REF }}
