name: .NET

on:  
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:Version=$GITHUB_REF --no-restore --configuration Release --output build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip
      run: tar -a -c -f polystone.zip build
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'release-$GITHUB_REF.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
