name: Release

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Slugs
      uses: rlespinasse/github-slug-action@v3.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=${{ env.GITHUB_REF_SLUG }} --output polystone-${{ env.GITHUB_REF_SLUG }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Zip
      run: tar -a -c -f polystone-${{ env.GITHUB_REF_SLUG }}.zip polystone-${{ env.GITHUB_REF_SLUG }}
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifact: polystone-${{ env.GITHUB_REF_SLUG }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
